### ISSUE TITLE
Eslintなど

### ISSUE THREAD

**Issue by MasaKusuda** [AkihiroKusuda/Yamitter#3]
コード整形ツールprittierとコード規約確認ツールeslintの設定がガバガバで競合しあってます．
設定を変更していい感じにしないといけない．

**Comment by AkihiroKusuda** [comment]
有益そうな情報メモ
 - https://blog.ojisan.io/eslint-prettier
 - https://qiita.com/shoichiimamura/items/0ba005889e3e90ee66d9
 - https://kic-yuuki.hatenablog.com/entry/2019/10/19/141601

**Comment by AkihiroKusuda** [comment]
eslintの設定はある程度まともになったと思う。
imgタグやbrタグが/'>'を持たないことにwarningを出すが、'<img ... />'のようにすることで解決できるため、prettierの設定で対応する。
prettierの設定や自動実行が**まだ**なので設定する必要がある。

参考
 - https://qiita.com/kiida/items/405bb07c4b52bfee0219
- https://eslint.vuejs.org/user-guide/#installation
